# given a blob and a COAX helicopter state, return the 3d position of the blob
# relative to the helicopter

coax_msgs/CoaxState state
cmvision/Blobs      blobs
uint8               blob_num
---
geometry_msgs/Point point
