
(in-package :asdf)

(defsystem "coax_msgs-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :coax_msgs-msg :roslib-msg)
  :components ((:file "_package")
    (:file "CoaxSetVerbose" :depends-on ("_package"))
    (:file "_package_CoaxSetVerbose" :depends-on ("_package"))
    (:file "CoaxGetSensorList" :depends-on ("_package"))
    (:file "_package_CoaxGetSensorList" :depends-on ("_package"))
    (:file "CoaxRequestState" :depends-on ("_package"))
    (:file "_package_CoaxRequestState" :depends-on ("_package"))
    (:file "CoaxSetRawControl" :depends-on ("_package"))
    (:file "_package_CoaxSetRawControl" :depends-on ("_package"))
    (:file "CoaxReset" :depends-on ("_package"))
    (:file "_package_CoaxReset" :depends-on ("_package"))
    (:file "CoaxConfigureComm" :depends-on ("_package"))
    (:file "_package_CoaxConfigureComm" :depends-on ("_package"))
    (:file "CoaxSetControlParameters" :depends-on ("_package"))
    (:file "_package_CoaxSetControlParameters" :depends-on ("_package"))
    (:file "CoaxSetAckMode" :depends-on ("_package"))
    (:file "_package_CoaxSetAckMode" :depends-on ("_package"))
    (:file "CoaxGetControlParameters" :depends-on ("_package"))
    (:file "_package_CoaxGetControlParameters" :depends-on ("_package"))
    (:file "CoaxConfigureControl" :depends-on ("_package"))
    (:file "_package_CoaxConfigureControl" :depends-on ("_package"))
    (:file "CoaxConfigureOAMode" :depends-on ("_package"))
    (:file "_package_CoaxConfigureOAMode" :depends-on ("_package"))
    (:file "CoaxSetLight" :depends-on ("_package"))
    (:file "_package_CoaxSetLight" :depends-on ("_package"))
    (:file "CoaxSetTrimMode" :depends-on ("_package"))
    (:file "_package_CoaxSetTrimMode" :depends-on ("_package"))
    (:file "CoaxGetVersion" :depends-on ("_package"))
    (:file "_package_CoaxGetVersion" :depends-on ("_package"))
    (:file "CoaxSetTimeout" :depends-on ("_package"))
    (:file "_package_CoaxSetTimeout" :depends-on ("_package"))
    (:file "CoaxSendString" :depends-on ("_package"))
    (:file "_package_CoaxSendString" :depends-on ("_package"))
    (:file "CoaxSetControl" :depends-on ("_package"))
    (:file "_package_CoaxSetControl" :depends-on ("_package"))
    (:file "CoaxGetTrimMode" :depends-on ("_package"))
    (:file "_package_CoaxGetTrimMode" :depends-on ("_package"))
    (:file "Coax3DSetControlMode" :depends-on ("_package"))
    (:file "_package_Coax3DSetControlMode" :depends-on ("_package"))
    (:file "CoaxReachNavState" :depends-on ("_package"))
    (:file "_package_CoaxReachNavState" :depends-on ("_package"))
    ))
