(in-package coax_msgs-msg)
(export '(HEADER-VAL
          ERRORFLAGS-VAL
          CONTENT-VAL
          TIMESTAMP-VAL
          CONTROLTIMEOUT-VAL
          WATCHDOGTIMEOUT-VAL
          MODE-VAL
          ROLL-VAL
          PITCH-VAL
          YAW-VAL
          GYRO-VAL
          ACCEL-VAL
          MAGNETO-VAL
          IMUTEMP-VAL
          ZRANGE-VAL
          ZFILTERED-VAL
          PRESSURE-VAL
          HRANGES-VAL
          XREL-VAL
          YREL-VAL
          BATTERY-VAL
          RCCHANNEL-VAL
          O_ATTITUDE-VAL
          O_ALTITUDE-VAL
          O_TOL-VAL
          O_XY-VAL
          O_OAVOID-VAL
))
