# Navigation mode: SB_NAV_... */
uint8 navigation
# Communication mode: SB_COM_... */
uint8 communication
# Obstacle avoidance mode: or of SB_OA_... */
uint8 oavoid
# Control mode for roll axis: SB_CTRL_... */
uint8 rollAxis
# Control mode for pitch axis: SB_CTRL_... */
uint8 pitchAxis
# Control mode for yaw axis: SB_CTRL_... */
uint8 yawAxis
# Control mode for altitude axis: SB_CTRL_... */
uint8 altAxis
