"""autogenerated by genmsg_py from CoaxVersion.msg. Do not edit."""
import roslib.message
import struct


class CoaxVersion(roslib.message.Message):
  _md5sum = "614a2e1fe797a467bac6f721b97ec4c0"
  _type = "coax_msgs/CoaxVersion"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 apiVersion
uint16 controllerVersion
string imuVersion
string compileTime

"""
  __slots__ = ['apiVersion','controllerVersion','imuVersion','compileTime']
  _slot_types = ['uint16','uint16','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       apiVersion,controllerVersion,imuVersion,compileTime
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(CoaxVersion, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.apiVersion is None:
        self.apiVersion = 0
      if self.controllerVersion is None:
        self.controllerVersion = 0
      if self.imuVersion is None:
        self.imuVersion = ''
      if self.compileTime is None:
        self.compileTime = ''
    else:
      self.apiVersion = 0
      self.controllerVersion = 0
      self.imuVersion = ''
      self.compileTime = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2H.pack(_x.apiVersion, _x.controllerVersion))
      _x = self.imuVersion
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.compileTime
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.apiVersion, _x.controllerVersion,) = _struct_2H.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.imuVersion = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.compileTime = str[start:end]
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2H.pack(_x.apiVersion, _x.controllerVersion))
      _x = self.imuVersion
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.compileTime
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.apiVersion, _x.controllerVersion,) = _struct_2H.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.imuVersion = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.compileTime = str[start:end]
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2H = struct.Struct("<2H")
