/* Auto-generated by genmsg_cpp for file /home/aaron/ros_pkgs/siue_coax_dev/ros_coax_dev/coax_msgs/srv/CoaxSetTrimMode.srv */
#ifndef COAX_MSGS_SERVICE_COAXSETTRIMMODE_H
#define COAX_MSGS_SERVICE_COAXSETTRIMMODE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"

#include "coax_msgs/CoaxTrimMode.h"



namespace coax_msgs
{
template <class ContainerAllocator>
struct CoaxSetTrimModeRequest_ : public ros::Message
{
  typedef CoaxSetTrimModeRequest_<ContainerAllocator> Type;

  CoaxSetTrimModeRequest_()
  : mode()
  {
  }

  CoaxSetTrimModeRequest_(const ContainerAllocator& _alloc)
  : mode(_alloc)
  {
  }

  typedef  ::coax_msgs::CoaxTrimMode_<ContainerAllocator>  _mode_type;
   ::coax_msgs::CoaxTrimMode_<ContainerAllocator>  mode;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxSetTrimModeRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ebb2d5a0e1488ca7b436e3a43853c58b"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "f44261c5d78b4d7c608cae2c0e15d49d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "CoaxTrimMode mode\n\
\n\
================================================================================\n\
MSG: coax_msgs/CoaxTrimMode\n\
# Trim mode, can be SB_TRIM_FROM_RC or SB_TRIM_SOFTWARE */\n\
uint8 trimMode \n\
# Trim position for the roll axis */\n\
float32 rollTrim\n\
# Trim position for the pitch axis */\n\
float32 pitchTrim\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, mode);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, mode);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(mode);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxSetTrimModeRequest
typedef  ::coax_msgs::CoaxSetTrimModeRequest_<std::allocator<void> > CoaxSetTrimModeRequest;

typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeRequest> CoaxSetTrimModeRequestPtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeRequest const> CoaxSetTrimModeRequestConstPtr;


template <class ContainerAllocator>
struct CoaxSetTrimModeResponse_ : public ros::Message
{
  typedef CoaxSetTrimModeResponse_<ContainerAllocator> Type;

  CoaxSetTrimModeResponse_()
  : result(0)
  {
  }

  CoaxSetTrimModeResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int8_t _result_type;
  int8_t result;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxSetTrimModeResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4414c67819626a1b8e0f043a9a0d6c9a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "f44261c5d78b4d7c608cae2c0e15d49d"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 result\n\
\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(result);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxSetTrimModeResponse
typedef  ::coax_msgs::CoaxSetTrimModeResponse_<std::allocator<void> > CoaxSetTrimModeResponse;

typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeResponse> CoaxSetTrimModeResponsePtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxSetTrimModeResponse const> CoaxSetTrimModeResponseConstPtr;

struct CoaxSetTrimMode
{

typedef CoaxSetTrimModeRequest Request;
typedef CoaxSetTrimModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CoaxSetTrimMode
} // namespace coax_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ebb2d5a0e1488ca7b436e3a43853c58b";
  }

  static const char* value(const  ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xebb2d5a0e1488ca7ULL;
  static const uint64_t static_value2 = 0xb436e3a43853c58bULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxSetTrimModeRequest";
  }

  static const char* value(const  ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CoaxTrimMode mode\n\
\n\
================================================================================\n\
MSG: coax_msgs/CoaxTrimMode\n\
# Trim mode, can be SB_TRIM_FROM_RC or SB_TRIM_SOFTWARE */\n\
uint8 trimMode \n\
# Trim position for the roll axis */\n\
float32 rollTrim\n\
# Trim position for the pitch axis */\n\
float32 pitchTrim\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const  ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxSetTrimModeResponse";
  }

  static const char* value(const  ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.mode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxSetTrimModeRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxSetTrimModeResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<coax_msgs::CoaxSetTrimMode> {
  static const char* value() 
  {
    return "f44261c5d78b4d7c608cae2c0e15d49d";
  }

  static const char* value(const coax_msgs::CoaxSetTrimMode&) { return value(); } 
};

template<>
struct DataType<coax_msgs::CoaxSetTrimMode> {
  static const char* value() 
  {
    return "coax_msgs/CoaxSetTrimMode";
  }

  static const char* value(const coax_msgs::CoaxSetTrimMode&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f44261c5d78b4d7c608cae2c0e15d49d";
  }

  static const char* value(const coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxSetTrimMode";
  }

  static const char* value(const coax_msgs::CoaxSetTrimModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f44261c5d78b4d7c608cae2c0e15d49d";
  }

  static const char* value(const coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxSetTrimMode";
  }

  static const char* value(const coax_msgs::CoaxSetTrimModeResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COAX_MSGS_SERVICE_COAXSETTRIMMODE_H

