/* Auto-generated by genmsg_cpp for file /home/aaron/ros_pkgs/siue_coax_dev/ros_coax_dev/coax_msgs/srv/CoaxReachNavState.srv */
#ifndef COAX_MSGS_SERVICE_COAXREACHNAVSTATE_H
#define COAX_MSGS_SERVICE_COAXREACHNAVSTATE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace coax_msgs
{
template <class ContainerAllocator>
struct CoaxReachNavStateRequest_ : public ros::Message
{
  typedef CoaxReachNavStateRequest_<ContainerAllocator> Type;

  CoaxReachNavStateRequest_()
  : desiredState(0)
  , timeout(0.0)
  {
  }

  CoaxReachNavStateRequest_(const ContainerAllocator& _alloc)
  : desiredState(0)
  , timeout(0.0)
  {
  }

  typedef uint8_t _desiredState_type;
  uint8_t desiredState;

  typedef float _timeout_type;
  float timeout;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxReachNavStateRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1ab80d04b4538d5252757e16aec7a55e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "9dad7fac31028e676b30d95151fbf893"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 desiredState\n\
float32 timeout\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, desiredState);
    ros::serialization::serialize(stream, timeout);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, desiredState);
    ros::serialization::deserialize(stream, timeout);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(desiredState);
    size += ros::serialization::serializationLength(timeout);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxReachNavStateRequest
typedef  ::coax_msgs::CoaxReachNavStateRequest_<std::allocator<void> > CoaxReachNavStateRequest;

typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateRequest> CoaxReachNavStateRequestPtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateRequest const> CoaxReachNavStateRequestConstPtr;


template <class ContainerAllocator>
struct CoaxReachNavStateResponse_ : public ros::Message
{
  typedef CoaxReachNavStateResponse_<ContainerAllocator> Type;

  CoaxReachNavStateResponse_()
  : result(0)
  {
  }

  CoaxReachNavStateResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int8_t _result_type;
  int8_t result;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxReachNavStateResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4414c67819626a1b8e0f043a9a0d6c9a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "9dad7fac31028e676b30d95151fbf893"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 result\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(result);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxReachNavStateResponse
typedef  ::coax_msgs::CoaxReachNavStateResponse_<std::allocator<void> > CoaxReachNavStateResponse;

typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateResponse> CoaxReachNavStateResponsePtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxReachNavStateResponse const> CoaxReachNavStateResponseConstPtr;

struct CoaxReachNavState
{

typedef CoaxReachNavStateRequest Request;
typedef CoaxReachNavStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CoaxReachNavState
} // namespace coax_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1ab80d04b4538d5252757e16aec7a55e";
  }

  static const char* value(const  ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1ab80d04b4538d52ULL;
  static const uint64_t static_value2 = 0x52757e16aec7a55eULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxReachNavStateRequest";
  }

  static const char* value(const  ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 desiredState\n\
float32 timeout\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const  ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxReachNavStateResponse";
  }

  static const char* value(const  ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.desiredState);
    stream.next(m.timeout);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxReachNavStateRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxReachNavStateResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<coax_msgs::CoaxReachNavState> {
  static const char* value() 
  {
    return "9dad7fac31028e676b30d95151fbf893";
  }

  static const char* value(const coax_msgs::CoaxReachNavState&) { return value(); } 
};

template<>
struct DataType<coax_msgs::CoaxReachNavState> {
  static const char* value() 
  {
    return "coax_msgs/CoaxReachNavState";
  }

  static const char* value(const coax_msgs::CoaxReachNavState&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9dad7fac31028e676b30d95151fbf893";
  }

  static const char* value(const coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxReachNavState";
  }

  static const char* value(const coax_msgs::CoaxReachNavStateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9dad7fac31028e676b30d95151fbf893";
  }

  static const char* value(const coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxReachNavState";
  }

  static const char* value(const coax_msgs::CoaxReachNavStateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COAX_MSGS_SERVICE_COAXREACHNAVSTATE_H

