/* Auto-generated by genmsg_cpp for file /home/aaron/ros_pkgs/siue_coax_dev/ros_coax_dev/coax_msgs/srv/CoaxConfigureComm.srv */
#ifndef COAX_MSGS_SERVICE_COAXCONFIGURECOMM_H
#define COAX_MSGS_SERVICE_COAXCONFIGURECOMM_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace coax_msgs
{
template <class ContainerAllocator>
struct CoaxConfigureCommRequest_ : public ros::Message
{
  typedef CoaxConfigureCommRequest_<ContainerAllocator> Type;

  CoaxConfigureCommRequest_()
  : commMode(0)
  , frequency(0)
  , numMessages(0)
  , contents(0)
  {
  }

  CoaxConfigureCommRequest_(const ContainerAllocator& _alloc)
  : commMode(0)
  , frequency(0)
  , numMessages(0)
  , contents(0)
  {
  }

  typedef uint8_t _commMode_type;
  uint8_t commMode;

  typedef uint16_t _frequency_type;
  uint16_t frequency;

  typedef uint16_t _numMessages_type;
  uint16_t numMessages;

  typedef uint32_t _contents_type;
  uint32_t contents;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxConfigureCommRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8bef03ada508431e00edf6ad2d960a31"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "0a4ffc01e802a3c95dac462243d2bddb"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 commMode\n\
uint16 frequency\n\
uint16 numMessages\n\
uint32 contents\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, commMode);
    ros::serialization::serialize(stream, frequency);
    ros::serialization::serialize(stream, numMessages);
    ros::serialization::serialize(stream, contents);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, commMode);
    ros::serialization::deserialize(stream, frequency);
    ros::serialization::deserialize(stream, numMessages);
    ros::serialization::deserialize(stream, contents);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(commMode);
    size += ros::serialization::serializationLength(frequency);
    size += ros::serialization::serializationLength(numMessages);
    size += ros::serialization::serializationLength(contents);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxConfigureCommRequest
typedef  ::coax_msgs::CoaxConfigureCommRequest_<std::allocator<void> > CoaxConfigureCommRequest;

typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommRequest> CoaxConfigureCommRequestPtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommRequest const> CoaxConfigureCommRequestConstPtr;


template <class ContainerAllocator>
struct CoaxConfigureCommResponse_ : public ros::Message
{
  typedef CoaxConfigureCommResponse_<ContainerAllocator> Type;

  CoaxConfigureCommResponse_()
  : result(0)
  {
  }

  CoaxConfigureCommResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int8_t _result_type;
  int8_t result;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxConfigureCommResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4414c67819626a1b8e0f043a9a0d6c9a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "0a4ffc01e802a3c95dac462243d2bddb"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 result\n\
\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(result);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxConfigureCommResponse
typedef  ::coax_msgs::CoaxConfigureCommResponse_<std::allocator<void> > CoaxConfigureCommResponse;

typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommResponse> CoaxConfigureCommResponsePtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureCommResponse const> CoaxConfigureCommResponseConstPtr;

struct CoaxConfigureComm
{

typedef CoaxConfigureCommRequest Request;
typedef CoaxConfigureCommResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CoaxConfigureComm
} // namespace coax_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8bef03ada508431e00edf6ad2d960a31";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8bef03ada508431eULL;
  static const uint64_t static_value2 = 0x00edf6ad2d960a31ULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureCommRequest";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 commMode\n\
uint16 frequency\n\
uint16 numMessages\n\
uint32 contents\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureCommResponse";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.commMode);
    stream.next(m.frequency);
    stream.next(m.numMessages);
    stream.next(m.contents);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxConfigureCommRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxConfigureCommResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<coax_msgs::CoaxConfigureComm> {
  static const char* value() 
  {
    return "0a4ffc01e802a3c95dac462243d2bddb";
  }

  static const char* value(const coax_msgs::CoaxConfigureComm&) { return value(); } 
};

template<>
struct DataType<coax_msgs::CoaxConfigureComm> {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureComm";
  }

  static const char* value(const coax_msgs::CoaxConfigureComm&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0a4ffc01e802a3c95dac462243d2bddb";
  }

  static const char* value(const coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureComm";
  }

  static const char* value(const coax_msgs::CoaxConfigureCommRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0a4ffc01e802a3c95dac462243d2bddb";
  }

  static const char* value(const coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureComm";
  }

  static const char* value(const coax_msgs::CoaxConfigureCommResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COAX_MSGS_SERVICE_COAXCONFIGURECOMM_H

