/* Auto-generated by genmsg_cpp for file /home/aaron/ros_pkgs/siue_coax_dev/ros_coax_dev/coax_msgs/srv/CoaxConfigureOAMode.srv */
#ifndef COAX_MSGS_SERVICE_COAXCONFIGUREOAMODE_H
#define COAX_MSGS_SERVICE_COAXCONFIGUREOAMODE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace coax_msgs
{
template <class ContainerAllocator>
struct CoaxConfigureOAModeRequest_ : public ros::Message
{
  typedef CoaxConfigureOAModeRequest_<ContainerAllocator> Type;

  CoaxConfigureOAModeRequest_()
  : oavoidMode(0)
  {
  }

  CoaxConfigureOAModeRequest_(const ContainerAllocator& _alloc)
  : oavoidMode(0)
  {
  }

  typedef uint16_t _oavoidMode_type;
  uint16_t oavoidMode;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxConfigureOAModeRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5a75af0b7b04132a12a56fe53fb7c53f"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c0668a37c3c443907202b387475fec72"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint16 oavoidMode\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, oavoidMode);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, oavoidMode);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(oavoidMode);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxConfigureOAModeRequest
typedef  ::coax_msgs::CoaxConfigureOAModeRequest_<std::allocator<void> > CoaxConfigureOAModeRequest;

typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeRequest> CoaxConfigureOAModeRequestPtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeRequest const> CoaxConfigureOAModeRequestConstPtr;


template <class ContainerAllocator>
struct CoaxConfigureOAModeResponse_ : public ros::Message
{
  typedef CoaxConfigureOAModeResponse_<ContainerAllocator> Type;

  CoaxConfigureOAModeResponse_()
  : result(0)
  {
  }

  CoaxConfigureOAModeResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int8_t _result_type;
  int8_t result;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxConfigureOAModeResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4414c67819626a1b8e0f043a9a0d6c9a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c0668a37c3c443907202b387475fec72"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 result\n\
\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(result);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxConfigureOAModeResponse
typedef  ::coax_msgs::CoaxConfigureOAModeResponse_<std::allocator<void> > CoaxConfigureOAModeResponse;

typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeResponse> CoaxConfigureOAModeResponsePtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureOAModeResponse const> CoaxConfigureOAModeResponseConstPtr;

struct CoaxConfigureOAMode
{

typedef CoaxConfigureOAModeRequest Request;
typedef CoaxConfigureOAModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CoaxConfigureOAMode
} // namespace coax_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5a75af0b7b04132a12a56fe53fb7c53f";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5a75af0b7b04132aULL;
  static const uint64_t static_value2 = 0x12a56fe53fb7c53fULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureOAModeRequest";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint16 oavoidMode\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureOAModeResponse";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.oavoidMode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxConfigureOAModeRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxConfigureOAModeResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<coax_msgs::CoaxConfigureOAMode> {
  static const char* value() 
  {
    return "c0668a37c3c443907202b387475fec72";
  }

  static const char* value(const coax_msgs::CoaxConfigureOAMode&) { return value(); } 
};

template<>
struct DataType<coax_msgs::CoaxConfigureOAMode> {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureOAMode";
  }

  static const char* value(const coax_msgs::CoaxConfigureOAMode&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0668a37c3c443907202b387475fec72";
  }

  static const char* value(const coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureOAMode";
  }

  static const char* value(const coax_msgs::CoaxConfigureOAModeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0668a37c3c443907202b387475fec72";
  }

  static const char* value(const coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureOAMode";
  }

  static const char* value(const coax_msgs::CoaxConfigureOAModeResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COAX_MSGS_SERVICE_COAXCONFIGUREOAMODE_H

