/* Auto-generated by genmsg_cpp for file /home/coax/ros_pkgs/siue_coax_dev/ros_coax_dev/coax_msgs/srv/CoaxGetControlParameters.srv */
#ifndef COAX_MSGS_SERVICE_COAXGETCONTROLPARAMETERS_H
#define COAX_MSGS_SERVICE_COAXGETCONTROLPARAMETERS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"



#include "coax_msgs/CoaxControlParameters.h"

namespace coax_msgs
{
template <class ContainerAllocator>
struct CoaxGetControlParametersRequest_ : public ros::Message
{
  typedef CoaxGetControlParametersRequest_<ContainerAllocator> Type;

  CoaxGetControlParametersRequest_()
  {
  }

  CoaxGetControlParametersRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxGetControlParametersRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4def45fbd3753b180c424ffdcb35116e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxGetControlParametersRequest
typedef  ::coax_msgs::CoaxGetControlParametersRequest_<std::allocator<void> > CoaxGetControlParametersRequest;

typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersRequest> CoaxGetControlParametersRequestPtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersRequest const> CoaxGetControlParametersRequestConstPtr;


template <class ContainerAllocator>
struct CoaxGetControlParametersResponse_ : public ros::Message
{
  typedef CoaxGetControlParametersResponse_<ContainerAllocator> Type;

  CoaxGetControlParametersResponse_()
  : params()
  {
  }

  CoaxGetControlParametersResponse_(const ContainerAllocator& _alloc)
  : params(_alloc)
  {
  }

  typedef  ::coax_msgs::CoaxControlParameters_<ContainerAllocator>  _params_type;
   ::coax_msgs::CoaxControlParameters_<ContainerAllocator>  params;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxGetControlParametersResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4def45fbd3753b180c424ffdcb35116e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4def45fbd3753b180c424ffdcb35116e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "CoaxControlParameters params\n\
\n\
\n\
\n\
================================================================================\n\
MSG: coax_msgs/CoaxControlParameters\n\
# Base thrust around which the control operates */\n\
float32 baseThrust\n\
# Difference of operating point between up and down motors */\n\
float32 yawOffset\n\
# Altitude gain: Kp*/\n\
float32 altitudeKp\n\
# Altitude gain: Ki*/\n\
float32 altitudeKi\n\
# Altitude gain: Kd*/\n\
float32 altitudeKd\n\
\n\
# Yaw gain: Kp*/\n\
float32 yawKp\n\
# Yaw gain: Ki*/\n\
float32 yawKi\n\
# Yaw gain: Kd*/\n\
float32 yawKd\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, params);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, params);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(params);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxGetControlParametersResponse
typedef  ::coax_msgs::CoaxGetControlParametersResponse_<std::allocator<void> > CoaxGetControlParametersResponse;

typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersResponse> CoaxGetControlParametersResponsePtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxGetControlParametersResponse const> CoaxGetControlParametersResponseConstPtr;

struct CoaxGetControlParameters
{

typedef CoaxGetControlParametersRequest Request;
typedef CoaxGetControlParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CoaxGetControlParameters
} // namespace coax_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxGetControlParametersRequest";
  }

  static const char* value(const  ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4def45fbd3753b180c424ffdcb35116e";
  }

  static const char* value(const  ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4def45fbd3753b18ULL;
  static const uint64_t static_value2 = 0x0c424ffdcb35116eULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxGetControlParametersResponse";
  }

  static const char* value(const  ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CoaxControlParameters params\n\
\n\
\n\
\n\
================================================================================\n\
MSG: coax_msgs/CoaxControlParameters\n\
# Base thrust around which the control operates */\n\
float32 baseThrust\n\
# Difference of operating point between up and down motors */\n\
float32 yawOffset\n\
# Altitude gain: Kp*/\n\
float32 altitudeKp\n\
# Altitude gain: Ki*/\n\
float32 altitudeKi\n\
# Altitude gain: Kd*/\n\
float32 altitudeKd\n\
\n\
# Yaw gain: Kp*/\n\
float32 yawKp\n\
# Yaw gain: Ki*/\n\
float32 yawKi\n\
# Yaw gain: Kd*/\n\
float32 yawKd\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxGetControlParametersRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.params);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxGetControlParametersResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<coax_msgs::CoaxGetControlParameters> {
  static const char* value() 
  {
    return "4def45fbd3753b180c424ffdcb35116e";
  }

  static const char* value(const coax_msgs::CoaxGetControlParameters&) { return value(); } 
};

template<>
struct DataType<coax_msgs::CoaxGetControlParameters> {
  static const char* value() 
  {
    return "coax_msgs/CoaxGetControlParameters";
  }

  static const char* value(const coax_msgs::CoaxGetControlParameters&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4def45fbd3753b180c424ffdcb35116e";
  }

  static const char* value(const coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxGetControlParameters";
  }

  static const char* value(const coax_msgs::CoaxGetControlParametersRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4def45fbd3753b180c424ffdcb35116e";
  }

  static const char* value(const coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxGetControlParameters";
  }

  static const char* value(const coax_msgs::CoaxGetControlParametersResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COAX_MSGS_SERVICE_COAXGETCONTROLPARAMETERS_H

