/* Auto-generated by genmsg_cpp for file /home/aaron/ros_pkgs/siue_coax_dev/ros_coax_dev/coax_msgs/srv/CoaxConfigureControl.srv */
#ifndef COAX_MSGS_SERVICE_COAXCONFIGURECONTROL_H
#define COAX_MSGS_SERVICE_COAXCONFIGURECONTROL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace coax_msgs
{
template <class ContainerAllocator>
struct CoaxConfigureControlRequest_ : public ros::Message
{
  typedef CoaxConfigureControlRequest_<ContainerAllocator> Type;

  CoaxConfigureControlRequest_()
  : rollMode(0)
  , pitchMode(0)
  , yawMode(0)
  , altitudeMode(0)
  {
  }

  CoaxConfigureControlRequest_(const ContainerAllocator& _alloc)
  : rollMode(0)
  , pitchMode(0)
  , yawMode(0)
  , altitudeMode(0)
  {
  }

  typedef uint16_t _rollMode_type;
  uint16_t rollMode;

  typedef uint16_t _pitchMode_type;
  uint16_t pitchMode;

  typedef uint16_t _yawMode_type;
  uint16_t yawMode;

  typedef uint16_t _altitudeMode_type;
  uint16_t altitudeMode;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxConfigureControlRequest"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a8b3c05573f16bc4305f15f017d3ee1c"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "3612d80e1bf1f78cf318a82336a878bf"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint16 rollMode\n\
uint16 pitchMode\n\
uint16 yawMode\n\
uint16 altitudeMode\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, rollMode);
    ros::serialization::serialize(stream, pitchMode);
    ros::serialization::serialize(stream, yawMode);
    ros::serialization::serialize(stream, altitudeMode);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, rollMode);
    ros::serialization::deserialize(stream, pitchMode);
    ros::serialization::deserialize(stream, yawMode);
    ros::serialization::deserialize(stream, altitudeMode);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(rollMode);
    size += ros::serialization::serializationLength(pitchMode);
    size += ros::serialization::serializationLength(yawMode);
    size += ros::serialization::serializationLength(altitudeMode);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxConfigureControlRequest
typedef  ::coax_msgs::CoaxConfigureControlRequest_<std::allocator<void> > CoaxConfigureControlRequest;

typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlRequest> CoaxConfigureControlRequestPtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlRequest const> CoaxConfigureControlRequestConstPtr;


template <class ContainerAllocator>
struct CoaxConfigureControlResponse_ : public ros::Message
{
  typedef CoaxConfigureControlResponse_<ContainerAllocator> Type;

  CoaxConfigureControlResponse_()
  : result(0)
  {
  }

  CoaxConfigureControlResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int8_t _result_type;
  int8_t result;


private:
  static const char* __s_getDataType_() { return "coax_msgs/CoaxConfigureControlResponse"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4414c67819626a1b8e0f043a9a0d6c9a"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "3612d80e1bf1f78cf318a82336a878bf"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 result\n\
\n\
\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, result);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(result);
    return size;
  }

  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct CoaxConfigureControlResponse
typedef  ::coax_msgs::CoaxConfigureControlResponse_<std::allocator<void> > CoaxConfigureControlResponse;

typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlResponse> CoaxConfigureControlResponsePtr;
typedef boost::shared_ptr< ::coax_msgs::CoaxConfigureControlResponse const> CoaxConfigureControlResponseConstPtr;

struct CoaxConfigureControl
{

typedef CoaxConfigureControlRequest Request;
typedef CoaxConfigureControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct CoaxConfigureControl
} // namespace coax_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a8b3c05573f16bc4305f15f017d3ee1c";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa8b3c05573f16bc4ULL;
  static const uint64_t static_value2 = 0x305f15f017d3ee1cULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureControlRequest";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint16 rollMode\n\
uint16 pitchMode\n\
uint16 yawMode\n\
uint16 altitudeMode\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureControlResponse";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.rollMode);
    stream.next(m.pitchMode);
    stream.next(m.yawMode);
    stream.next(m.altitudeMode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxConfigureControlRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoaxConfigureControlResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<coax_msgs::CoaxConfigureControl> {
  static const char* value() 
  {
    return "3612d80e1bf1f78cf318a82336a878bf";
  }

  static const char* value(const coax_msgs::CoaxConfigureControl&) { return value(); } 
};

template<>
struct DataType<coax_msgs::CoaxConfigureControl> {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureControl";
  }

  static const char* value(const coax_msgs::CoaxConfigureControl&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3612d80e1bf1f78cf318a82336a878bf";
  }

  static const char* value(const coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureControl";
  }

  static const char* value(const coax_msgs::CoaxConfigureControlRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3612d80e1bf1f78cf318a82336a878bf";
  }

  static const char* value(const coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "coax_msgs/CoaxConfigureControl";
  }

  static const char* value(const coax_msgs::CoaxConfigureControlResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // COAX_MSGS_SERVICE_COAXCONFIGURECONTROL_H

